# alerts_dashboard.py
# Streamlit dashboard for live low stock alerts with filters and quick charts.

import os
from datetime import datetime
import joblib
import pandas as pd
import plotly.express as px
import streamlit as st

ROOT = os.getcwd()
OUT_DIR = os.path.join(ROOT, "output")
ALERT_LATEST = os.path.join(OUT_DIR, "low_stock_alert_latest.csv")
DATA_CSV = os.path.join(OUT_DIR, "retail_dataset.csv")

st.set_page_config(page_title="Retail. Reorder Alerts", layout="wide")

st.title("SKU Reorder Alerts")
st.caption("Generated by the pipeline. Filter and export as needed.")

if not os.path.exists(ALERT_LATEST):
    st.warning("No alert file found. Run retail_pipeline.py first.")
    st.stop()

alerts = pd.read_csv(ALERT_LATEST)
data = pd.read_csv(DATA_CSV) if os.path.exists(DATA_CSV) else None

# filters
c1, c2, c3, c4 = st.columns(4)
regions = ["All"] + sorted(alerts["region"].dropna().unique().tolist())
states = ["All"] + sorted(alerts["state"].dropna().unique().tolist())
cities = ["All"] + sorted(alerts["city"].dropna().unique().tolist())
cats = ["All"] + sorted(alerts["category"].dropna().unique().tolist())

with c1:
    f_region = st.selectbox("Region", regions)
with c2:
    f_state = st.selectbox("State", states)
with c3:
    f_city = st.selectbox("City", cities)
with c4:
    f_cat = st.selectbox("Category", cats)

f_alerts = alerts.copy()
if f_region != "All":
    f_alerts = f_alerts[f_alerts["region"] == f_region]
if f_state != "All":
    f_alerts = f_alerts[f_alerts["state"] == f_state]
if f_city != "All":
    f_alerts = f_alerts[f_alerts["city"] == f_city]
if f_cat != "All":
    f_alerts = f_alerts[f_alerts["category"] == f_cat]

# headline metrics
st.metric("SKUs at or below reorder", len(f_alerts))
if data is not None:
    total_sales = data["sales"].sum()
    st.metric("Total Sales in dataset", f"{total_sales:,.0f}")

# charts
colA, colB = st.columns(2)
with colA:
    if "state" in f_alerts.columns:
        by_state = f_alerts.groupby("state", as_index=False)["sku"].count().rename(columns={"sku": "count"}).sort_values("count", ascending=False)
        st.plotly_chart(px.bar(by_state, x="state", y="count", title="Low stock count by state"), use_container_width=True)
with colB:
    if "store_code" in f_alerts.columns:
        by_store = f_alerts.groupby("store_code", as_index=False)["sku"].count().rename(columns={"sku": "count"}).sort_values("count", ascending=False).head(20)
        st.plotly_chart(px.bar(by_store, x="store_code", y="count", title="Top stores by low stock count"), use_container_width=True)

st.subheader("Alert details")
st.dataframe(f_alerts, use_container_width=True, hide_index=True)

st.download_button(
    "Download filtered alerts CSV",
    data=f_alerts.to_csv(index=False).encode("utf-8"),
    file_name=f"low_stock_alert_filtered_{datetime.now():%Y%m%d}.csv"
)

